# Generated by Django 3.1.1 on 2020-11-20 04:11

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=300)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Time', models.TimeField(blank=True, null=True)),
                ('Event', models.TextField(choices=[('Volunteer', 'Volunteer'), ('Donation', 'Donation')], max_length=10)),
                ('xp', models.IntegerField(default=10)),
                ('Datetime', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True, validators=[base.models.valid_duration])),
                ('amount_received', models.FloatField(default=0.0)),
                ('signup_list', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login', models.BooleanField(default=True)),
                ('phoneNum', models.CharField(blank=True, max_length=20)),
                ('exp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('is_volunteer', models.BooleanField(default=True)),
                ('event_history', models.ManyToManyField(related_name='event_history', to='base.Create')),
                ('submitted_donation', models.ManyToManyField(related_name='submitted_donation', to='base.Create')),
                ('submitted_volunteer', models.ManyToManyField(related_name='submitted_volunteer', to='base.Create')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
