# Generated by Django 3.1.1 on 2020-11-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201120_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
